config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#get 'top' => 'homes#top'
get "home/about" => "homes#about", as: "about"
root to: 'homes#top'

# resources :post_images, only: [:new, :create, :index, :show, :destroy] do
resources :books, only: [:top, :new, :create, :index, :show, :edit, :update, :destroy] do
resource :favorites, only: [:create, :destroy]
resources :book_comments, only: [:create, :destroy]
end

# resources :books, only: [:top, :new, :create, :index, :show, :edit, :update, :destroy]
resources :users, only: [:top, :show, :edit, :index, :update]
resources :posts, only: [:index, :show, :create]

end

# resources :posts do
#   resource :favorites, only: [:create, :destroy]
# end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
   
 def favorited_by?(user)
   favorites.exists?(user_id: user.id)
 end
   
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
  # def favorited_by?(user)
  # favorites.exists?(user_id: user.id)
  # end
end

app/models/post.rb
# class Post < ApplicationRecord
#   belongs_to :user
#   has_many :favorites, dependent: :destroy
# end

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
   
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
   has_many :books, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
  # has_many :favorite_books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
   def after_sign_out_path_for(resource)
    root_path
   end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    # @books=Book.find(params[:id])
    @books = Book.find(params[:book_id])
    @book_comment = BookComment.new
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @books.id
    if comment.save
      redirect_to book_path(@books)
      flash[:notice] = "Comment was successfully created."
    else
      @error_comment = comment
      # @book_image = BookImage.find(params[:book_image_id])
      @book_comment = BookComment.new
      redirect_to request.referer
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = current_user
    redirect_to request.referer
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
    redirect_to request.referer
    # redirect_to ("/posts/#{params[:post_id]}")
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def new
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully created."
    else
      @books = Book.all
      @user = current_user

      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
    # if @user = current_user
    #   redirect_to book_path
    # end
  end

  def edit
    @book = Book.find(params[:id])
     if @book.user != current_user
       redirect_to books_path
     end
  end

   def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
     @user = current_user
     @books = Book.all
     render :edit
    end
   end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

   def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
   end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    redirect_to request.referer
end

def index
    @book = Book.find(params[:id])
end

def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to request.referer
end








  # def create
  #   @book_favorite = Favorite.new(user_id: current_user.id, book_id: params[:book_id])
  #   @book_favorite.save
  #   redirect_to books_path
  # end

  # def destroy
  #   @book_favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
  #   @book_favorite.destroy
  #   redirect_to books_path
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    flash[:notice] = "Signed out successfully."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
    flash[:notice] = "Welcome! You have signed up successfully."
  end
  
  def show
    flash[:notice] = "Signed in successfully."
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  
  def index
    @users = User.all
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
  if @user != current_user
    redirect_to user_path(current_user)
  end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path
    else
     render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/show.html.erb
<td>
  <%= "コメント数: #{@book.book_comments.count}" %>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %>

    <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
    <% end %>
  <% end %>
</td>
<%= form_with model: [@book, @book_comment] do |f| %>

<% if @error_comment.present? %>
    <div id="error_explanation">
      <h2><%= @error_comment.errors.count %> error prohibited this obj from being saved: </h2>
      <ul>
        <% @error_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.text_area :comment, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.submit "送信" %>
</div>
  <% end %>
</div>

app/views/books/edit.html.erb
<!--<p id="notice">You have updated book successfully.</p>-->
 <!--%= flash[:notice] %>-->
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    
  <h1>Editing Book</h1>
  
  <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  
<%= form_with model: @book do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title", class: "d-block" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion", class: "d-block" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.submit 'Update Book', class: "btn btn-success" %>
  </div>
  <% end %>
  
      <%= link_to "Show", book_path %>
      |
      <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>

app/views/books/index.html.erb
 <div class="container px-5 px-sm-0">
   <% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

    <div class="row">
      <div class="col-md-3">
        <%= render 'users/info', user: @user, book: @book %>
        </div>
  <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title,book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>

      <td>
    <% if book.favorited_by?(current_user) %>

  <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fas fa-heart text-danger"></i>
<% end %>
<% else %>

  <%= link_to book_favorites_path(book), method: :post do %>
 <i class="fas fa-heart"></i>
 <% end %>
 <% end %>
  </td>
  <td>
    <%= " #{book.favorites.count} " %>
  </td>

<td>
<%= "コメント数: #{book.book_comments.count}" %>
</td>
    </tr>
  <% end %>


  <!--%= image_tag book.get_image %-->
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<!--<p id="notice">You have created book successfully.</p>-->
 <%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/info', user: @user, book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %></br>
              <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title,book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>

    <td>
    <% if @book.favorited_by?(current_user) %>

    <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fas fa-heart text-danger"></i>
    <% end %>

    <% else %>

    <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="fas fa-heart"></i>
    <% end %>

    <% end %>
    </td>
    <td>
    <%= " #{@book.favorites.count} " %>
    </td>
      <td><%= "コメント数: #{@book.book_comments.count}" %></td>
      
    <% if @book.user == current_user %>
    <td>
    <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
    </td>
    <% end %>
    <% if @book.user == current_user %>
    <td>
    <%= link_to "Destroy", book_path(@book.id), class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>
    </td>
    <% end %>
      
      
  <table>
  <% @book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= book_comment.comment %></td>
    <td><p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %></td>

    <% if book_comment.user == current_user %>
      <td>
        <!--%= link_to "Destroy", book_path, class:"btn btn-sm btn-danger", method: :delete %>-->
    <!--%= link_to("Destroy", "/comments/#{c.id}/destroy") %>-->
     <%= link_to "Destroy", book_book_comment_path(book_id: @book.id, id: book_comment.id), class:"btn btn-sm btn-danger", method: :delete %>
    <!--(@post_comment.id)-->
        </td>


    <% end %>
  </tr>
  <% end %>
  </table>
  
  </tr>
  </tbody>
  </table>
           
      <!--    </tr>-->
      <!--  </tbody>-->
      <!--</table>-->
  <%= form_with model: [@book, @book_comment] do |f| %>
<div class="form-group">
    <%= f.text_area :comment, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.submit "送信" %>
</div>
  <% end %>
</div>


    </div>
  </div>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to 
    <i class= "fas fa-book"></i>
    <strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/homes/top.html.erb
<main>
        <%= flash[:notice] %>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class= "fas fa-book"></i>
      </h1>
      <p>In  <i class= "fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <!--<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>-->
          <%= link_to "Log in",new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <!--<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>-->
          <%= link_to "Sign up",new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
          <span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
            <i class= "fas fa-home" ></i> Home
            <% end %>
            </li>

            <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
              <i class= "fas fa-users"></i> Users
              <% end %>
           </li>
           <li>
              <%= link_to books_path, class: "nav-link text-light" do %>
           <i class= "fas fa-book-open"></i> Books
           <% end %>
           </li>
           <li>
             <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
           <i class= "fas fa-sign-out-alt"></i> Log out
           <% end %>
           </li>
            <% else %>
            <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
            <i class= "fas fa-home" ></i> Home
            <% end %>
            </li>

            <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
              <i class= "fas fa-link"></i> About
              <% end %>
           </li>
           <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
           <i class= "fas fa-user-plus"></i> Sign up
           <% end %>
           </li>
           <li>
             <%= link_to new_user_session_path, class: "nav-link text-light" do %>
           <i class= "fas fa-sign-in-alt"></i> Log in
           <% end %>
           </li>
           <% end %>

            </ul>
          </div>
          </div>
          </nav>
          </header>
          <main>
            <%= yield %>
          </main> 
          

<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
     </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
    </tr>
    <tr>
	  <th>introduction</th>
	 <th><%= user.introduction %></th>
	  </tr>
  </tbody>
</table>

<div class="row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class= "fas fa-user-cog"></i>
  <% end %>
</div>

<h2>New book</h2>

  <%= form_with model: book do |f| %>
  
  <div class="form-group">
    <%= f.label :title, "Title", class: "d-block" %>
  <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion", class: "d-block" %>
  <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
  <% end %>
  

app/views/users/edit.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
<h2>User info</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>

<div class="form-group">
  <%= f.label :title, "Name", class: "d-block" %>
  <%= f.text_field :name, class: "form-control" %>
</div>
  
<div class="form-group">
  <%= f.label :user_image, "Image", class: "d-block" %>
  <input class="form-control-file user_image" accept="image/*" type="file" name="user[profile_image]" id="user_profile_image">
<!--%= f.file_field :user_image, placeholder: "プロフィール画像", accept: "image/*" %>-->
</div>
      
<div class="form-group">
  <%= f.label :text, "Introduction", class: "d-block" %>
  <%= f.text_field :introduction, class: "form-control" %>
</div>
  
<div class="form-group">
  <%= f.submit 'Update User', class: "btn btn-secondary" %>
</div>

<% end%>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/info', user: current_user, book: @book %>
        </div>
  <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= image_tag user.get_profile_image(100,100) %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= link_to "Show", user_path(user.id) %>

      </td>
    </tr>
    <% end %>
    
  <!--%= image_tag book.get_image %-->
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--<div>-->
<!--  <h3>%= @user.name %></h3>-->
<!--  %= image_tag @user.get_profile_image(100,100) %>-->
<!--</div>-->
<%= flash[:notice] %>
 <div class="container px-5 px-sm-0">
<!--<div class="container">-->
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/info', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">

<!-- ユーザーの投稿一覧 -->

<!--% @books.each do |book| %>-->
<!--<div>-->
<!--  %= link_to book_path(book.id) do %>-->
    <!--%= image_tag post_image.get_image %-->
<!--  % end %>-->
<!--  %= image_tag book.user.get_profile_image(100,100) %>-->
<!--  %= book.title %>-->
<!--  %= book.body %>-->
<!--</div>-->
<!--% end %>-->

<h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title,book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>

      <td>
    <% if book.favorited_by?(current_user) %>

    <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fas fa-heart text-danger"></i>
    <% end %>
    <% else %>

    <%= link_to book_favorites_path(book), method: :post do %>
        <i class="fas fa-heart"></i>
    <% end %>
    <% end %>
    </td>

    <td>
    <%= " #{book.favorites.count} " %>
    </td>

    <td>
      <%= "コメント数: #{book.book_comments.count}" %>
    </td>

    </tr>
    <% end %>
    </tbody>
  </table>
    </div>
  </div>
</div>
</div>

app/views/users/top.html.erb
<h1>Users#top</h1>
<p>Find me in app/views/users/top.html.erb</p>